Titlte: Dịch vụ
'@extends': default

form:
  fields:
    header.services:
      type: list
      label: Danh sách dịch vụ
      style: vertical
      fields:
        .title:
          type: text
          label: Tiêu đề
          validate:
            required: true

        .subtitle:
          type: text
          label: Tiêu đề phụ
          validate:
            required: false

        .short_description:
          type: textarea
          label: Mô tả ngắn
          validate:
            required: false

        .description:
          type: textarea
          label: Mô tả chi tiết
          validate:
            required: true

        .link:
          type: text
          label: Liên kết
          placeholder: '#'
          validate:
            required: false

        .image:
          type: file
          label: Hình ảnh
          multiple: false
          destination: 'self@'
          accept:
            - image/*
          validate:
            required: false

    header.subtitle:
      type: text
      label: Tiêu đề phụ
      validate:
        required: false
  # process:
  #   save:
  #     fileprefix: 'service-'
  #     filename: 'item'
  #   custom: 'create_service_page'
  #   message: "Dịch vụ đã được tạo thành công!"
