title: Default
'@extends': default

form:
  fields:
    tabs:
      type: tabs
      active: 1
      fields:
        content:
          type: tab
          title: Nội dung
          fields:
            content:
              type: markdown
              label: "Nội dung chính"
              validate:
                required: true

            banner:
              type: text
              label: "Tiêu đề Banner"

            sidebar:
              type: textarea
              label: "Nội dung Sidebar"

            footer:
              type: editor
              label: "Nội dung Footer"

            content1:
              type: textarea
              label: "Content 1"

            content2:
              type: textarea
              label: "Content 2"
